"""Terracotta-vs-custom 99th-percentile (P99) latency comparison (data-analysis output).

Builds on :mod:`common.latency` (latency histogram -> CDF -> percentile). For each technique it
aggregates every experiment's latency dump into a CDF and reports the P99 latency of the
Terracotta implementation against its custom implementation, per core setup. Emits a plain-text
report ending in a proposed paper sentence (§8.5.2).

Reporting groups (purely about which numbers form the headline claim; the metric is the same
P99 latency for every technique):
  * ``base``     -- ChargeCache, MASA, MoPAC-C: four-core only (the setup the submission's latency
                    scripts used); the headline is the worst four-core P99 overhead.
  * ``prada``    -- PRADA: both bank configurations are shown; the reported number is the more
                    demanding one (1 bank), mirroring how the base techniques report four-core.

Output: ``results/txt/latency_comparison.txt`` -- a reproduction OUTPUT (regenerated by the
parse pipeline; not committed, like the other results/ artifacts). Run standalone or via
``parse_results.sh``.
"""

import argparse
import os
import sys

from common import latency
from common.manifest import load_manifest

# Per-technique comparison spec. `custom`/`terra` are the exact manifest variant names paired
# against each other; `grouper`/`pick` select the CDF group (MoPAC splits by nRH -> pick 250,
# the representative RowHammer threshold used throughout the figures). `headline` is the setup
# whose number enters the summary claim (base uses four_core; PRADA combines its setups).
COMPARISONS = [
    dict(tech="chargecache", disp="ChargeCache", custom="custom", terra="terracotta",
         setups=["four_core"], grouper="variant", group="base",
         headline="four_core"),
    dict(tech="masa", disp="MASA", custom="custom", terra="terracotta",
         setups=["four_core"], grouper="variant", group="base",
         headline="four_core"),
    dict(tech="mopac", disp="MoPAC-C", custom="custom", terra="terracotta",
         setups=["four_core"], grouper="variant_sweep", pick="250",
         group="base", headline="four_core"),
    dict(tech="prada", disp="PRADA", custom="custom", terra="terracotta",
         setups=["single_core", "single_core_1b"], grouper="variant", group="prada",
         headline="single_core_1b",
         setup_label={"single_core": "32 banks", "single_core_1b": "1 bank"}),
]

DEFAULT_OUT = "results/txt/latency_comparison.txt"
P = 99  # the only percentile reported


def _group_key(table, var, grouper, pick):
    """Resolve the CDF group key for a variant. `variant` grouper -> exact name; `variant_sweep`
    -> the key beginning exactly ``<var>_<pick>`` (so 'terracotta' does not swallow
    'terracotta_latency', and the requested sweep point is selected)."""
    if grouper == "variant":
        return var if var in table else None
    prefix = f"{var}_{pick}"
    cands = [k for k in table if k.startswith(prefix)]
    return sorted(cands)[0] if cands else None


def compare(results_root="results", techniques_root="techniques"):
    """Return (rows, notes). Each row: dict(tech, disp, group, setup, setup_label, headline,
    custom_p99, terra_p99, pct99). Techniques/setups without latency dumps are skipped."""
    rows, notes = [], []
    for spec in COMPARISONS:
        try:
            mani = load_manifest(os.path.join(techniques_root, spec["tech"]))
        except Exception as exc:
            notes.append(f"{spec['disp']}: manifest load failed ({exc})")
            continue
        for setup in spec["setups"]:
            rd = os.path.join(results_root, spec["tech"], setup)
            if not os.path.isdir(os.path.join(rd, "latency")):
                notes.append(f"{spec['disp']}/{setup}: no latency/ dir")
                continue
            groups, seen, missing = latency.collect(
                mani, setup, rd, latency.GROUPERS[spec["grouper"]])
            table = latency.percentile_table(groups, (P,))
            ck = _group_key(table, spec["custom"], spec["grouper"], spec.get("pick"))
            tk = _group_key(table, spec["terra"], spec["grouper"], spec.get("pick"))
            if ck is None or tk is None:
                notes.append(f"{spec['disp']}/{setup}: missing custom/terra CDF "
                             f"(custom={ck}, terra={tk}; {seen} seen, {missing} missing)")
                continue
            cp99, tp99 = table[ck][P], table[tk][P]
            pct99 = 100.0 * (tp99 / cp99 - 1.0) if cp99 else float("nan")
            rows.append(dict(
                tech=spec["tech"], disp=spec["disp"], group=spec["group"], setup=setup,
                setup_label=spec.get("setup_label", {}).get(setup, setup),
                headline=spec["headline"], custom_p99=cp99, terra_p99=tp99, pct99=pct99))
    return rows, notes


def _sentence(rows):
    """Compose the proposed paper sentence (§8.5.2 structure)."""
    parts = []
    base_hl = [r for r in rows if r["group"] == "base" and r["setup"] == r["headline"]]
    if base_hl:
        worst = max(base_hl, key=lambda r: r["pct99"])
        names = ", ".join(sorted({r["disp"] for r in base_hl}))
        parts.append(
            f"Across {names}, Terracotta implementations increase the four-core 99th-percentile "
            f"latency by at most {worst['pct99']:.2f}% over their custom implementations.")
    prada = [r for r in rows if r["group"] == "prada"]
    if prada:
        worst = max(prada, key=lambda r: r["pct99"])   # the more demanding config (1 bank)
        split = ", ".join(f"{r['pct99']:+.1f}% at {r['setup_label']}"
                          for r in sorted(prada, key=lambda r: r["setup_label"]))
        parts.append(f"For PRADA, the 99th-percentile latency overhead is {worst['pct99']:+.1f}% "
                     f"at its most demanding configuration ({split}).")
    return " ".join(parts)


def render(rows, notes):
    """Render the full text report as a string."""
    L = []
    L.append("Terracotta vs custom -- 99th-percentile (P99) latency")
    L.append("=" * 64)
    L.append("Source: results/<technique>/<core_setup>/latency/*.core* (regenerable output).")
    L.append("Latencies in memory cycles; P99 via linear interpolation on the latency CDF")
    L.append(f"(LLC hits <= {latency.CACHE_HIT_THRESHOLD} cycles excluded). Each Terracotta")
    L.append("implementation is paired against its custom implementation.")
    L.append("")
    hdr = f"{'technique':17s}{'setup':11s}{'custom P99':>12s}{'terra P99':>12s}{'dP99':>10s}"
    L.append(hdr)
    L.append("-" * len(hdr))
    for r in rows:
        L.append(f"{r['disp']:17s}{r['setup_label']:11s}"
                 f"{r['custom_p99']:12.1f}{r['terra_p99']:12.1f}{r['pct99']:+9.2f}%")
    L.append("")
    L.append("Summary")
    L.append("-" * 64)
    base_hl = [r for r in rows if r["group"] == "base" and r["setup"] == r["headline"]]
    if base_hl:
        lo = min(base_hl, key=lambda r: r["pct99"])
        hi = max(base_hl, key=lambda r: r["pct99"])
        L.append(f"  Base techniques, four-core (ChargeCache, MASA, MoPAC-C): P99 overhead in "
                 f"[{lo['pct99']:+.2f}%, {hi['pct99']:+.2f}%]; max {hi['pct99']:+.2f}% ({hi['disp']}).")
    prada = [r for r in rows if r["group"] == "prada"]
    if prada:
        worst = max(prada, key=lambda r: r["pct99"])
        for r in sorted(prada, key=lambda r: r["setup_label"]):
            L.append(f"  PRADA {r['setup_label']:9s}: P99 {r['pct99']:+.2f}% "
                     f"(custom {r['custom_p99']:.0f} -> terra {r['terra_p99']:.0f} cycles).")
        L.append(f"  PRADA reported  : P99 {worst['pct99']:+.2f}% ({worst['setup_label']} -- the "
                 f"more demanding config, mirroring four-core for the base techniques).")
    for n in notes:
        L.append(f"  NOTE: {n}")
    L.append("")
    L.append("PROPOSED PAPER SENTENCE (edit as needed):")
    L.append("  " + _sentence(rows))
    L.append("")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results-root", default="results")
    ap.add_argument("--techniques-root", default="techniques")
    ap.add_argument("-o", "--out", default=DEFAULT_OUT)
    args = ap.parse_args()

    rows, notes = compare(args.results_root, args.techniques_root)
    if not rows:
        print("[latency_comparison] ERROR: no latency dumps found under "
              f"{args.results_root}/<technique>/<core_setup>/latency/", file=sys.stderr)
        for n in notes:
            print(f"  NOTE: {n}", file=sys.stderr)
        return 1
    report = render(rows, notes)
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w") as f:
        f.write(report)
    print(report)
    print(f"[latency_comparison] wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
